import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Instagram App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      <Header />

      {/* Feed */}

      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Animi nulla
        voluptatibus, aliquid provident sint numquam magni nostrum molestiae
        consectetur obcaecati id in repudiandae ipsum esse veritatis? Corrupti
        voluptatibus labore omnis iste sequi beatae corporis blanditiis quis
        tempore aliquam tenetur ipsam provident ea saepe, consectetur optio
        voluptas autem alias vitae laboriosam? Placeat, ea modi dignissimos
        molestiae nulla consequuntur eveniet pariatur tempore mollitia minima
        adipisci expedita rerum! Ea quidem, cum, ducimus odit hic ad quod atque
        dolore quasi, saepe unde magnam repellendus laborum libero provident
        temporibus deserunt sunt quibusdam veritatis? Sed temporibus sequi quam
        necessitatibus, in sit placeat fugiat tenetur autem porro!
      </p>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Animi nulla
        voluptatibus, aliquid provident sint numquam magni nostrum molestiae
        consectetur obcaecati id in repudiandae ipsum esse veritatis? Corrupti
        voluptatibus labore omnis iste sequi beatae corporis blanditiis quis
        tempore aliquam tenetur ipsam provident ea saepe, consectetur optio
        voluptas autem alias vitae laboriosam? Placeat, ea modi dignissimos
        molestiae nulla consequuntur eveniet pariatur tempore mollitia minima
        adipisci expedita rerum! Ea quidem, cum, ducimus odit hic ad quod atque
        dolore quasi, saepe unde magnam repellendus laborum libero provident
        temporibus deserunt sunt quibusdam veritatis? Sed temporibus sequi quam
        necessitatibus, in sit placeat fugiat tenetur autem porro!
      </p>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Animi nulla
        voluptatibus, aliquid provident sint numquam magni nostrum molestiae
        consectetur obcaecati id in repudiandae ipsum esse veritatis? Corrupti
        voluptatibus labore omnis iste sequi beatae corporis blanditiis quis
        tempore aliquam tenetur ipsam provident ea saepe, consectetur optio
        voluptas autem alias vitae laboriosam? Placeat, ea modi dignissimos
        molestiae nulla consequuntur eveniet pariatur tempore mollitia minima
        adipisci expedita rerum! Ea quidem, cum, ducimus odit hic ad quod atque
        dolore quasi, saepe unde magnam repellendus laborum libero provident
        temporibus deserunt sunt quibusdam veritatis? Sed temporibus sequi quam
        necessitatibus, in sit placeat fugiat tenetur autem porro!
      </p>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Animi nulla
        voluptatibus, aliquid provident sint numquam magni nostrum molestiae
        consectetur obcaecati id in repudiandae ipsum esse veritatis? Corrupti
        voluptatibus labore omnis iste sequi beatae corporis blanditiis quis
        tempore aliquam tenetur ipsam provident ea saepe, consectetur optio
        voluptas autem alias vitae laboriosam? Placeat, ea modi dignissimos
        molestiae nulla consequuntur eveniet pariatur tempore mollitia minima
        adipisci expedita rerum! Ea quidem, cum, ducimus odit hic ad quod atque
        dolore quasi, saepe unde magnam repellendus laborum libero provident
        temporibus deserunt sunt quibusdam veritatis? Sed temporibus sequi quam
        necessitatibus, in sit placeat fugiat tenetur autem porro!
      </p>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Animi nulla
        voluptatibus, aliquid provident sint numquam magni nostrum molestiae
        consectetur obcaecati id in repudiandae ipsum esse veritatis? Corrupti
        voluptatibus labore omnis iste sequi beatae corporis blanditiis quis
        tempore aliquam tenetur ipsam provident ea saepe, consectetur optio
        voluptas autem alias vitae laboriosam? Placeat, ea modi dignissimos
        molestiae nulla consequuntur eveniet pariatur tempore mollitia minima
        adipisci expedita rerum! Ea quidem, cum, ducimus odit hic ad quod atque
        dolore quasi, saepe unde magnam repellendus laborum libero provident
        temporibus deserunt sunt quibusdam veritatis? Sed temporibus sequi quam
        necessitatibus, in sit placeat fugiat tenetur autem porro!
      </p>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Animi nulla
        voluptatibus, aliquid provident sint numquam magni nostrum molestiae
        consectetur obcaecati id in repudiandae ipsum esse veritatis? Corrupti
        voluptatibus labore omnis iste sequi beatae corporis blanditiis quis
        tempore aliquam tenetur ipsam provident ea saepe, consectetur optio
        voluptas autem alias vitae laboriosam? Placeat, ea modi dignissimos
        molestiae nulla consequuntur eveniet pariatur tempore mollitia minima
        adipisci expedita rerum! Ea quidem, cum, ducimus odit hic ad quod atque
        dolore quasi, saepe unde magnam repellendus laborum libero provident
        temporibus deserunt sunt quibusdam veritatis? Sed temporibus sequi quam
        necessitatibus, in sit placeat fugiat tenetur autem porro!
      </p>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Animi nulla
        voluptatibus, aliquid provident sint numquam magni nostrum molestiae
        consectetur obcaecati id in repudiandae ipsum esse veritatis? Corrupti
        voluptatibus labore omnis iste sequi beatae corporis blanditiis quis
        tempore aliquam tenetur ipsam provident ea saepe, consectetur optio
        voluptas autem alias vitae laboriosam? Placeat, ea modi dignissimos
        molestiae nulla consequuntur eveniet pariatur tempore mollitia minima
        adipisci expedita rerum! Ea quidem, cum, ducimus odit hic ad quod atque
        dolore quasi, saepe unde magnam repellendus laborum libero provident
        temporibus deserunt sunt quibusdam veritatis? Sed temporibus sequi quam
        necessitatibus, in sit placeat fugiat tenetur autem porro!
      </p>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Animi nulla
        voluptatibus, aliquid provident sint numquam magni nostrum molestiae
        consectetur obcaecati id in repudiandae ipsum esse veritatis? Corrupti
        voluptatibus labore omnis iste sequi beatae corporis blanditiis quis
        tempore aliquam tenetur ipsam provident ea saepe, consectetur optio
        voluptas autem alias vitae laboriosam? Placeat, ea modi dignissimos
        molestiae nulla consequuntur eveniet pariatur tempore mollitia minima
        adipisci expedita rerum! Ea quidem, cum, ducimus odit hic ad quod atque
        dolore quasi, saepe unde magnam repellendus laborum libero provident
        temporibus deserunt sunt quibusdam veritatis? Sed temporibus sequi quam
        necessitatibus, in sit placeat fugiat tenetur autem porro!
      </p>

      {/* Modal */}
    </div>
  )
}
